<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class AiMonthlyInsight extends Model
{
    use HasFactory;

    public const STATUS_AI_GENERATED = 'ai_generated';
    public const STATUS_FALLBACK = 'fallback';
    public const STATUS_FAILED = 'failed';

    protected $fillable = [
        'user_id',
        'month',
        'summary',
        'highlights',
        'actions',
        'status',
        'provider',
        'model',
        'metadata',
        'generated_at',
    ];

    protected $casts = [
        'highlights' => 'array',
        'actions' => 'array',
        'metadata' => 'array',
        'generated_at' => 'datetime',
    ];

    /**
     * The insight belongs to a User.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Scope for a specific user.
     */
    public function scopeForUser(Builder $query, int $userId): Builder
    {
        return $query->where('user_id', $userId);
    }

    /**
     * Scope for a specific month (YYYY-MM).
     */
    public function scopeForMonth(Builder $query, string $month): Builder
    {
        return $query->where('month', $month);
    }

    /**
     * Check if the insight was generated by an external AI model.
     */
    public function isAiGenerated(): bool
    {
        return $this->status === self::STATUS_AI_GENERATED;
    }

    /**
     * Check if the insight is an automated deterministic fallback.
     */
    public function isFallback(): bool
    {
        return $this->status === self::STATUS_FALLBACK;
    }

    /**
     * Get human-readable month label (e.g., "September 2026").
     */
    public function getFormattedMonthAttribute(): string
    {
        try {
            return Carbon::createFromFormat('Y-m', $this->month)->format('F Y');
        } catch (\Exception $e) {
            return $this->month;
        }
    }
}
